[package]
name = "thrift_tutorial_server"
version = "0.1.0"
authors = ["SimonX <simonxiao@qq.com>"]
edition = "2018"

[dependencies]
thrift = "0.12.0"
ordered-float = "0.3.0"
try_from = "0.2.0"
clap  = "2.32.0"
thrift_tutorial = { path = "../thrift_tutorial" }